name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3.1.2
        with:
          node-version: "20"

      - name: Set up Go
        uses: actions/setup-go@v3.1.2
        with:
          go-version: "1.16"

      - name: Build app
        run: scripts/buildprod.sh
